name: Cypress Tests

on:
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browsers: [chrome, firefox, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run in ${{ matrix.browsers }}
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browsers }}
          reporter: 'cypress-mochawesome-reporter' # Explicitly set the reporter
          reporterOptions: 'reportDir=cypress/reports/${{ matrix.browsers }}/.jsons,overwrite=false,html=false,json=true'
      - name: Merge Mochawesome Reports
        run: npx mochawesome-merge "cypress/reports/${{ matrix.browsers }}/.jsons/*.json" > cypress/reports/${{ matrix.browsers }}/merged-reports.json
      - name: Generate HTML Reports
        run: npx marge cypress/reports/${{ matrix.browsers }}/merged-reports.json --reportDir cypress/reports/${{ matrix.browsers }} -f "${{ matrix.browsers }}-report.html"
      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: Cypress HTML Report ${{ matrix.browsers }}
          path: cypress/reports/${{ matrix.browsers }}
      - name: Upload Screenshots on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Cypress Screenshots ${{ matrix.browsers }}
          path: cypress/screenshots
      - name: Upload Videos on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Cypress Videos ${{ matrix.browsers }}
          path: cypress/videos
