name: Cypress Tests

on:
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browsers: [chrome, firefox, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run in ${{ matrix.browsers }}
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browsers }}
          command: npx cypress run --browser ${{ matrix.browsers }} --reporter mochawesome --reporter-options reportDir=cypress/reports/${{ matrix.browsers }},overwrite=false,html=false,json=true

      - name: Merge Mochawesome Reports
        run: npx mochawesome-merge "cypress/reports/${{ matrix.browsers }}/*.json" > "cypress/reports/${{ matrix.browsers }}/merged-reports.json"
        if: always() # Ensure this step runs even if Cypress tests fail

      - name: Generate HTML Reports
        run: npx marge "cypress/reports/${{ matrix.browsers }}/merged-reports.json" -o "cypress/reports/${{ matrix.browsers }}" -f "${{ matrix.browsers }}-report"
        if: always() # Ensure this step runs even if merging fails

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
<<<<<<< HEAD
            name: Cypress HTML Report ${{ matrix.browsers }}
            path: cypress/reports/${{ matrix.browsers }}


=======
          name: Cypress HTML Report ${{ matrix.browsers }}
          path: cypress/reports/${{ matrix.browsers }}
        if: always() # Ensure this step runs even if report generation fails
>>>>>>> ec79595901122090b67f7b39beb352ec16aef973
