name: Cypress Tests Debug

on:
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        browsers: [chrome, firefox, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run in ${{ matrix.browsers }}
        uses: cypress-io/github-action@v6
        with:
          browser: ${{ matrix.browsers }}
      - name: Merge Mochawesome Reports
        continue-on-error: true
        run: npx mochawesome-merge "cypress/mochawesome-report/*.json" > cypress/reports/html/merged-reports-${{ matrix.browsers }}.json
      - name: Generate HTML Reports
        continue-on-error: true
        run: |
          echo "Generating HTML report for ${{ matrix.browsers }}"
          npx marge cypress/reports/html/merged-reports-${{ matrix.browsers }}.json --reportDir cypress/reports/html -f "${{ matrix.browsers }}-report.html"
          echo "HTML report generation complete."
      - name: List Report Directory Contents
        continue-on-error: true
        run: ls -lR cypress/reports/html
      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: Cypress HTML Report ${{ matrix.browsers }}
          path: cypress/reports/html
      - name: Upload Screenshots on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Cypress Screenshots ${{ matrix.browsers }}
          path: cypress/screenshots
      - name: Upload Videos on Failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Cypress Videos ${{ matrix.browsers }}
          path: cypress/videos
